"""init

Revision ID: 93fc8c5d3cc1
Revises: 
Create Date: 2024-12-09 08:06:46.231645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93fc8c5d3cc1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('memory_usage', sa.FLOAT(), nullable=False),
    sa.Column('cpu_usage', sa.FLOAT(), nullable=False),
    sa.Column('disk_spaca_total', sa.INTEGER(), nullable=False),
    sa.Column('disk_space_used', sa.INTEGER(), nullable=False),
    sa.Column('disk_usage', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metrics'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metrics')
    # ### end Alembic commands ###
